import Head from 'next/head'
import Script from 'next/script'
import { Header } from '#components/Header'
import { Container } from '#components/Container'

import { Products } from '#components/Products'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://app.snipcart.com" />
      <link rel="preconnect" href="https://cdn.snipcart.com" />
      <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css" />
    </Head>
    <Header />
    <main>
      <Container>
        <h2>Available Cards</h2>
        <Products />
      </Container>
    </main>
    <footer>
      <Container>
        wooo
      </Container>
    </footer>
    <Script src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js" />
    <div hidden id="snipcart" data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}></div>
    </>
  )
}
