import Head from 'next/head'
import { Header } from '#components/Header'
import { Container } from '#components/Container'

import { Products } from '#components/Products'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main>
      <Container>
        <h2>Available Cards</h2>
        <Products />
      </Container>
    </main>
    <footer>
      <Container>
        wooo
      </Container>
    </footer>
    </>
  )
}
